### ISSUE TITLE
Unhandled Runtime Error `postcss/postcss` from `0.3.1` to `8.3.6`

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#314]
### Describe the bug

When comparing `postcss/postcss` releases from `0.3.1` to `8.3.6`, I get a error:

```
Unhandled Runtime Error

TypeError: mdastNode.children is undefined
```

### Give the steps to reproduce

1. Go to `main` branch of our code, run `yarn`
1. `yarn start` to get the local development server running
1. Go to `http://localhost:3000/comparator?repo=postcss%2Fpostcss&from=0.3.1&to=8.3.6`
1. See error

### What browsers are you seeing the problem on?

Firefox

### Have you thought of a possible solution?

No

### Do you want to help fix the bug?

No

**Comment by Belco90** [comment]
Interesting error. I think I have an idea why it happens and might be even fixed in #302. Let's see what happens with this issue after merging that PR!

**Comment by HonkingGoose** [comment]
I'll try to keep an eye out if this changes things.

Might also be a good "test-case" for a unit/integration test, to verify that this bug is fixed, and remains fixed? If we ever get around to doing those things. 😄

**Comment by HonkingGoose** [comment]
This is still a problem on current `main` even after merging #302 which:

> The whole unified/rehype/remark ecosystem is upgraded and working fine with Next.js v11.1 now.

**Comment by Belco90** [comment]
This needs further investigation then.

**Comment by Belco90** [comment]
This is solved now! After the types improvements I did on #533, where I had to add some extra checks to make sure there weren't type errors, now this comparison doesn't trigger an error anymore.

You can see that here: https://octoclairvoyant.vercel.app/comparator?repo=postcss%2Fpostcss&from=0.3.1&to=8.3.6

Still, the comparison it's a bit weird, but I think that's a different thing. Should we close this one then?

**Comment by HonkingGoose** [comment]
> This is solved now! After the types improvements I did on #533, where I had to add some extra checks to make sure there weren't type errors, now this comparison doesn't trigger an error anymore.

Yay! 🥳

> Still, the comparison it's a bit weird, but I think that's a different thing. Should we close this one then?

What do you mean with "a bit weird"?

**Comment by Belco90** [comment]
There are a few of these groups in the middle of the result:

![CleanShot 2021-11-08 at 11 08 30@2x](https://user-images.githubusercontent.com/2677072/140731729-8530c315-9e12-42ce-be29-2c3fe71fcc01.png)

We can't do nothing about those from now, it seems those releases didn't follow proper sem ver.

**Comment by HonkingGoose** [comment]
The problem with the groups deserves its own issue, if we want to fix it.

I'll close this issue as we have fixed the unhandled runtime error that this bug report is about. 😄
